package com.badsoft.android.log2db.entity;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LOG".
 */
@Entity
public class LOG implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;
    private String CODE;

    @NotNull
    private java.util.Date CREATEDATE;
    private String PREETYDATE;
    private String MESSAGE;
    private String STACKTRACE;
    private String TYPE;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public LOG() {
    }

    public LOG(Long id) {
        this.id = id;
    }

    @Generated
    public LOG(Long id, String CODE, java.util.Date CREATEDATE, String PREETYDATE, String MESSAGE, String STACKTRACE, String TYPE) {
        this.id = id;
        this.CODE = CODE;
        this.CREATEDATE = CREATEDATE;
        this.PREETYDATE = PREETYDATE;
        this.MESSAGE = MESSAGE;
        this.STACKTRACE = STACKTRACE;
        this.TYPE = TYPE;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCODE() {
        return CODE;
    }

    public void setCODE(String CODE) {
        this.CODE = CODE;
    }

    @NotNull
    public java.util.Date getCREATEDATE() {
        return CREATEDATE;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCREATEDATE(@NotNull java.util.Date CREATEDATE) {
        this.CREATEDATE = CREATEDATE;
    }

    public String getPREETYDATE() {
        return PREETYDATE;
    }

    public void setPREETYDATE(String PREETYDATE) {
        this.PREETYDATE = PREETYDATE;
    }

    public String getMESSAGE() {
        return MESSAGE;
    }

    public void setMESSAGE(String MESSAGE) {
        this.MESSAGE = MESSAGE;
    }

    public String getSTACKTRACE() {
        return STACKTRACE;
    }

    public void setSTACKTRACE(String STACKTRACE) {
        this.STACKTRACE = STACKTRACE;
    }

    public String getTYPE() {
        return TYPE;
    }

    public void setTYPE(String TYPE) {
        this.TYPE = TYPE;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
